export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const LOAD_PRODUCT = 'LOAD_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SUBMIT_LEAVE = 'SUBMIT_LEAVE';
export const LOAD_APPROVER = 'LOAD_APPROVER';
export const LOAD_UPPERMANAGER = 'LOAD_UPPERMANAGER';
export const LOAD_LEAVETYPE = 'LOAD_LEAVETYPE';
export const UPDATE_LEAVE = 'UPDATE_LEAVE';

export const LOAD_MEMBER_REPORT = 'LOAD_MEMBER_REPORT';

export const DECLINE_LEAVE = 'DECLINE_LEAVE';
export const LOAD_LEAVESTATISTIC = 'LOAD_LEAVESTATISTIC';
export const LOAD_LEAVE = 'LOAD_LEAVE';
export const APPROVE_LEAVE = 'APPROVE_LEAVE';
export const ADD_LEAVE = 'ADD_LEAVE';
export const DELETE_LEAVE = 'DELETE_LEAVE';
export const UPLOAD_LEAVE_FILES = 'UPLOAD_LEAVE_FILES';
export const CALCULATE_LEAVE_HOURS = 'CALCULATE_LEAVE_HOURS';
export const SUBMIT_MY_LEAVE = 'SUBMIT_MY_LEAVE';
export const LOAD_MY_LEAVE_BALANCES = 'LOAD_MY_LEAVE_BALANCES';

//leave
export const LOAD_MY_LEAVES = 'LOAD_MY_LEAVES';
export const LOAD_EMPLOYEE_LEAVES = 'LOAD_EMPLOYEE_LEAVES';
export const LOAD_EMPLOYEE_LEAVE_BALANCES = 'LOAD_EMPLOYEE_LEAVE_BALANCES';

//Setting
export const LOAD_LEAVE_SETTING = 'LOAD_LEAVE_SETTING';
export const UPDATE_LEAVE_SETTING = 'UPDATE_LEAVE_SETTING';
export const UPDATE_SETTING = 'UPDATE_SETTING';

//Setting shift categories
export const LOAD_SHIFTCATEGORIES_SETTING = 'LOAD_SHIFTCATEGORIES_SETTING';
export const LOAD_SHIFTCATEGORY_SETTING = 'LOAD_SHIFTCATEGORY_SETTING';
export const EDIT_SHIFTCATEGORY_SETTING = 'EDIT_SHIFTCATEGORY_SETTING';
export const DELETE_SHIFTCATEGORY_SETTING = 'DELETE_SHIFTCATEGORY_SETTING';

//Setting skills management
export const LOAD_SKILLS_SETTING = 'LOAD_SKILLS_SETTING';
export const LOAD_SKILL_SETTING = 'LOAD_SKILL_SETTING';
export const ADD_SKILL_SETTING = 'ADD_SKILL_SETTING';
export const EDIT_SKILL_SETTING = 'EDIT_SKILL_SETTING';
export const DELETE_SKILL_SETTING = 'DELETE_SKILL_SETTING';

//Setting Region management
export const LOAD_REGIONS_SETTING = 'LOAD_REGIONS_SETTING';
export const LOAD_REGION_DETAIL = 'LOAD_REGION_DETAIL';
export const LOAD_REGION_SETTING = 'LOAD_REGION_SETTING';
export const ADD_REGION_SETTING = 'ADD_REGION_SETTING';
export const EDIT_REGION_SETTING = 'EDIT_SKILL_SETTING';
export const DELETE_REGION_SETTING = 'DELETE_REGION_SETTING';

//Setting Location management
export const LOAD_LOCATIONS_SETTING = 'LOAD_LOCATIONS_SETTING';
export const LOAD_ALL_LOCATIONS_SETTING = 'LOAD_ALL_LOCATIONS_SETTING';
export const LOAD_LOCATIONS_OF_REGIONID = 'LOAD_LOCATIONS_OF_REGIONID';
export const LOAD_LOCATION_SETTING = 'LOAD_LOCATION_SETTING';
export const ADD_LOCATION_SETTING = 'ADD_LOCATION_SETTING';
export const EDIT_LOCATION_SETTING = 'EDIT_LOCATION_SETTING';
export const DELETE_LOCATION_SETTING = 'DELETE_LOCATION_SETTING';
export const UPDATE_LOCATION_DTO = 'UPDATE_LOCATION_DTO';
export const UPDATE_FULL_LOCATION_DTO = 'UPDATE_FULL_LOCATION_DTO';


//Setting Shift Template
export const LOAD_SHIFTTEMPLATES_SETTING = 'LOAD_SHIFTTEMPLATES_SETTING';
export const LOAD_SHIFTTEMPLATE_SETTING = 'LOAD_SHIFTTEMPLATE_SETTING';
export const ADD_SHIFTTEMPLATE_SETTING = 'ADD_SHIFTTEMPLATE_SETTING';
export const EDIT_SHIFTTEMPLATES_SETTING = 'EDIT_SHIFTTEMPLATES_SETTING';
export const DELETE_SHIFTTEMPLATES_SETTING = 'DELETE_SHIFTTEMPLATES_SETTING';

export const LOAD_SHIFT_TEMPLATES = 'LOAD_SHIFT_TEMPLATES';

//Setting Job Role management
export const LOAD_JOBROLES_SETTING = 'LOAD_JOBROLES_SETTING';
export const LOAD_JOBROLE_SETTING = 'LOAD_JOBROLE_SETTING';
export const ADD_JOBROLES_SETTING = 'ADD_JOBROLES_SETTING';
export const EDIT_JOBROLES_SETTING = 'EDIT_JOBROLES_SETTING';
export const DELETE_JOBROLES_SETTING = 'DELETE_JOBROLES_SETTING';

//Setting User Role management
export const LOAD_USERROLES_SETTING = 'LOAD_USERROLES_SETTING';
export const LOAD_USERROLE_SETTING = 'LOAD_USERROLE_SETTING';
export const ADD_USERROLES_SETTING = 'ADD_USERROLES_SETTING';
export const EDIT_USERROLES_SETTING = 'EDIT_USERROLES_SETTING';
export const DELETE_USERROLES_SETTING = 'DELETE_USERROLES_SETTING';

//// global
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_ERROR = 'RESET_ERROR';
export const RESET_STATE = 'RESET_STATE';
export const LOADING = 'LOADING';
export const SWITCH_TYPE_PAYLOAD = 'SWITCH_TYPE_PAYLOAD';
export const SET_VISIBILITY_APPBAR = 'SET_VISIBILITY_APPBAR';
export const CLONE = 'CLONE';
export const RESET_SCHEDULE_STATE = 'RESET_SCHEDULE_STATE';
export const RESET_SCHEDULE_SHIFTVIEW_STATE = 'RESET_SCHEDULE_SHIFTVIEW_STATE';
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE';
export const RESET_SETTING_STATE = 'RESET_SETTING_STATE';
export const RESET_LOCATION_STATE = 'RESET_LOCATION_STATE'

/////Timesheets
export const LOAD_SUBMITTER_TIMESHEETS = 'LOAD_SUBMITTER_TIMESHEETS';
export const LOAD_TEAM_TIMESHEETS = 'LOAD_TEAM_TIMESHEETS';
export const ADD_EDIT_TIMESHEET = 'ADD_EDIT_TIMESHEET';
export const LOAD_TIMESHEET = 'LOAD_TIMESHEET';
export const EDIT_TIMESHEET = 'EDIT_TIMESHEET';
export const DELETE_TIMESHEET = 'DELETE_TIMESHEET';
export const UPDATE_DTO_TIMESHEET = 'UPDATE_DTO_TIMESHEET';
export const UPDATE_PAYLOAD_TIMESHEET = 'UPDATE_PAYLOAD_TIMESHEET';
export const LOAD_WORKINGSTATUS = 'LOAD_WORKINGSTATUS';
export const POST_WORKINGSTATUS = 'POST_WORKINGSTATUS';

export const LOAD_MY_TIMESHEETS = 'LOAD_MY_TIMESHEETS';
export const LOAD_EMPLOYEE_TIMESHEETS = 'LOAD_EMPLOYEE_TIMESHEETS';
export const LOAD_TIMESHEET_TYPE = 'LOAD_TIMESHEET_TYPE';
export const LOAD_TIMESHEETS_EMPLOYEE = 'LOAD_TIMESHEETS_EMPLOYEE';
export const APPROVE_TIMESHEETS = 'APPROVE_TIMESHEETS';
export const APPROVE_ALL_TIMESHEETS = 'APPROVE_ALL_TIMESHEETS';
export const LOAD_ALL_PENDINGS_TIMESHEETS = 'LOAD_ALL_PENDINGS_TIMESHEETS';
export const UPDATE_TIMESHEET = 'UPDATE_TIMESHEET';
export const LOAD_TIMESHEET_SETTING = 'LOAD_TIMESHEET_SETTING';
export const LOAD_GROUP_TIMESHEETS = 'LOAD_GROUP_TIMESHEETS';
export const SUBMIT_TEAM_TIMESHEETS = 'SUBMIT_TEAM_TIMESHEETS';
export const LOAD_GROUP_STATUS_TIMESHEETS = 'LOAD_GROUP_STATUS_TIMESHEETS';
export const LOAD_EMPLOYEE_TIMESHEET_HISTORIES = 'LOAD_EMPLOYEE_TIMESHEET_HISTORIES';
export const LOAD_TIMESHEET_HISTORY_EMPLOYEE = 'LOAD_TIMESHEET_HISTORY_EMPLOYEE';
export const LOAD_GROUP_TIMESHEETS_HISTORY = 'LOAD_GROUP_TIMESHEETS_HISTORY';
export const LOAD_APPROVER_GROUP_TIMESHEETS_HISTORY = 'LOAD_APPROVER_GROUP_TIMESHEETS_HISTORY';

//login
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOAD_EMPLOYEE_AFTER_LOGIN_SUCCESS = 'LOAD_EMPLOYEE_AFTER_LOGIN_SUCCESS';
export const LOGIN_FIRST = 'LOGIN_FIRST';
export const CHANGEPASSWORD_FAIL = 'CHANGEPASSWORD_FAIL';
export const CHANGEPASSWORD_SUCESS = 'CHANGEPASSWORD_SUCESS';
export const FORGOTPASSWORD_SUCCESS = 'FORGOTPASSWORD_SUCCESS';
export const FORGOTPASSWORD_FAIL = 'FORGOTPASSWORD_FAIL';
export const CHANGEFORGETPASSWORD = 'CHANGEFORGETPASSWORD';
export const VALIDTOKEN_SUCCESS = 'VALIDTOKEN_SUCCESS';
export const VALIDTOKEN_FAIL = 'VALIDTOKEN_FAIL';
export const RESETPASSWORD = 'RESETPASSWORD';
export const CONFIRMPASSWORD = 'CONFIRMPASSWORD';

//Employee
export const LOAD_EMPLOYEE = 'LOAD_EMPLOYEE';
export const LOAD_ALL_EMPLOYEE = 'LOAD_ALL_EMPLOYEE';
export const LOAD_ALL_BASE_EMPLOYEE = 'LOAD_ALL_BASE_EMPLOYEE';
export const LOAD_MEMBERS_OF_EMPLOYEE = 'LOAD_MEMBERS_OF_EMPLOYEE';
export const GET_MEMBERS = 'GET_MEMBERS';
export const LOAD_EMPLOYEE_ASSIGN = 'LOAD_EMPLOYEE_ASSIGN';

//Employee Type
export const LOAD_ALL_EMPLOYEE_TYPES = 'LOAD_ALL_EMPLOYEE_TYPES';

//Employee Setting
export const LOAD_AVAILABILITY_SETTING = 'LOAD_AVAILABILITY_SETTING';
export const LOAD_WORKINGTIME_SETTING = 'LOAD_WORKINGTIME_SETTING';


//Customer
export const LOAD_ALL_CUSTOMER = 'LOAD_ALL_CUSTOMER';
export const LOAD_CUSTOMER = 'LOAD_CUSTOMER';
export const UPLOAD_CUSTOMER_FILES = 'UPLOAD_CUSTOMER_FILES';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const UPDATE_CUSTOMER_DTO = 'UPDATE_CUSTOMER_DTO';
export const CHANGE_CUSTOMER_AVATAR = 'CHANGE_CUSTOMER_AVATAR';

//Department
export const ADD_GROUP = 'ADD_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const LOAD_GROUP = 'LOAD_GROUP';
export const LOAD_ALL_GROUP = 'LOAD_ALL_GROUP';
export const LOAD_ALL_BASE_GROUP = 'LOAD_ALL_BASE_GROUP';
export const LOAD_ALL_STATE = 'LOAD_ALL_STATE';
export const LOAD_GROUPS_SUB = 'LOAD_GROUPS_SUB';
export const LOAD_SCHEDULE_GROUPS_SUB = 'LOAD_SCHEDULE_GROUPS_SUB';
export const LOAD_MANAGED_GROUPS = 'LOAD_MANAGED_GROUPS';

//Department Type
export const ADD_GROUP_TYPE = 'ADD_GROUP_TYPE';
export const EDIT_GROUP_TYPE = 'EDIT_GROUP_TYPE';
export const DELETE_GROUP_TYPE = 'DELETE_GROUP_TYPE';
export const LOAD_GROUP_TYPE = 'LOAD_GROUP_TYPE';
export const LOAD_ALL_GROUP_TYPE = 'LOAD_ALL_GROUP_TYPE';
export const LOAD_ALL_SUPERVISOR = 'LOAD_ALL_SUPERVISOR';


//Employee portal
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const UPDATE_EMPLOYEE_DTO = 'UPDATE_EMPLOYEE_DTO';
export const RESET_EMPLOYEE_DTO = 'RESET_EMPLOYEE_DTO';
export const RESET_NEW_EMPLOYEE_DTO = 'RESET_NEW_EMPLOYEE_DTO';
export const UPDATE_OVERTIME_DTO = 'UPDATE_OVERTIME_DTO';
export const UPDATE_REQUEST_OTEMPLOYEES = 'UPDATE_REQUEST_OTEMPLOYEES';
export const VALIDATE_EMAIL_EMPLOYEE = 'VALIDATE_EMAIL_EMPLOYEE';
export const VALIDATE_WORKINGPHONE_EMPLOYEE = 'VALIDATE_WORKINGPHONE_EMPLOYEE';
export const VALIDATE_ACCOUNT_EMPLOYEE = 'VALIDATE_ACCOUNT_EMPLOYEE';
export const VALIDATE_FIELD_EMPLOYEE = 'VALIDATE_FIELD_EMPLOYEE';
export const VALIDATE_TOTAL_FIELD_EMPLOYEE = 'VALIDATE_TOTAL_FIELD_EMPLOYEE';
export const RESET_VALIDATE = 'RESET_VALIDATE';
export const EDIT_EMPLOYEE_CONTACT_DETAIL = 'EDIT_EMPLOYEE_CONTACT_DETAIL';
export const EDIT_EMPLOYEE_JOB = 'EDIT_EMPLOYEE_JOB';
export const EDIT_EMPLOYEE_TIME = 'EDIT_EMPLOYEE_TIME';
export const EDIT_EMPLOYEE_PAY_RATE = 'EDIT_EMPLOYEE_PAY_RATE';
export const IMPORT_EMPLOYEE = 'IMPORT_EMPLOYEE';
export const EXPORT_EMPLOYEES = 'EXPORT_EMPLOYEES';
export const LOAD_EMPLOYEE_HANDSETS = 'LOAD_EMPLOYEE_HANDSETS';
export const RETURN_HANDSET = 'RETURN_HANDSET';
export const LOAD_EMPLOYEE_TRANSFERS = 'LOAD_EMPLOYEE_TRANSFERS';
export const TRANSFER_EMPLOYEE = 'TRANSFER_EMPLOYEE';

//My Profile
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOAD_PROFILE_TIME = 'LOAD_PROFILE_TIME';
export const LOAD_PROFILE_ATTACHMENT = 'LOAD_PROFILE_ATTACHMENT';
export const LOAD_PROFILE_JOBROLE_SKILLS = 'LOAD_PROFILE_JOBROLE_SKILLS';
export const LOAD_PROFILE_CONTACTDETAIL = 'LOAD_PROFILE_CONTACTDETAIL';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_CONTACTDETAIL = 'EDIT_PROFILE_CONTACTDETAIL';
export const UPDATE_MY_PROFILE_DTO = 'UPDATE_MY_PROFILE_DTO';
export const LOAD_MY_APPROVERS = 'LOAD_MY_APPROVERS';

//Upload
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR';
export const UPLOAD_CV = 'UPLOAD_CV';
export const UPLOAD_FILES = 'UPLOAD_FILES';
export const DELETE_FILE = 'DELETE_FILE';
export const UPLOAD_CERTIFICATE = 'UPLOAD_CERTIFICATE';
export const UPDATE_FILES_DTO = 'UPDATE_FILES_DTO';
export const RESET_STATE_DIALOG_ATTACH_FILE = 'RESET_STATE_DIALOG_ATTACH_FILE';

//RequiredDocument
export const LOAD_REQUIREDDOCUMENTS_SETTING = 'LOAD_REQUIREDDOCUMENTS_SETTING';
export const LOAD_REQUIREDDOCUMENT_SETTING = 'LOAD_REQUIREDDOCUMENT_SETTING';
export const ADD_REQUIREDDOCUMENT_SETTING = 'ADD_REQUIREDDOCUMENT_SETTING';
export const EDIT_REQUIREDDOCUMENT_SETTING = 'EDIT_REQUIREDDOCUMENT_SETTING';
export const DELETE_REQUIREDDOCUMENT_SETTING = 'DELETE_REQUIREDDOCUMENT_SETTING';

//Schedule Management
export const LOAD_SCHEDULES = 'LOAD_SCHEDULES';
export const LOAD_SCHEDULE = 'LOAD_SCHEDULE';
export const LOAD_EMPLOYEE_SCHEDULES = 'LOAD_EMPLOYEE_SCHEDULES';
export const LOAD_MY_SCHEDULES = 'LOAD_MY_SCHEDULES';
export const ADD_SCHEDULE = 'ADD_SCHEDULE'

//Leave Management
export const LOAD_LEAVEMANAGEMENT_SETTING = 'LOAD_LEAVEMANAGEMENT_SETTING';
export const UPDATE_LEAVEMANAGEMENT_DTO = 'UPDATE_LEAVEMANAGEMENT_DTO';
export const UPDATE_RAWLEAVECONFIG_DTO = 'UPDATE_RAWLEAVECONFIG_DTO';
export const EDIT_LEAVEMANAGEMENT_SETTING = 'EDIT_LEAVEMANAGEMENT_SETTING';
export const LOAD_ALL_LEAVETYPES = 'LOAD_ALL_LEAVETYPES';

//General Setting
export const LOAD_GENERAL_SETTING = 'LOAD_GENERAL_SETTING';
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

//Roles Management
export const LOAD_ROLES = 'LOAD_ROLES';
export const LOAD_ROLE_DETAIL = 'LOAD_ROLE_DETAIL';
export const ADD_ROLE = 'ADD_ROLE';
export const EDIT_ROLE = 'EDIT_ROLE';
export const DELETE_ROLE = 'DELETE_ROLE';
export const LOAD_ACCESS_RIGHTS = 'LOAD_ACCESS_RIGHTS';
export const UPDATE_ROLE_DTO = 'UPDATE_ROLE_DTO';
//Overtime Management
export const LOAD_ALL_RECEIVED_REQUESTS = 'LOAD_ALL_RECEIVED_REQUESTS';
export const LOAD_ALL_SENT_REQUESTS = 'LOAD_ALL_SENT_REQUESTS';
export const EDIT_OVERTIME = 'EDIT_OVERTIME';
export const ADD_NEW_OVERTIME = 'ADD_NEW_OVERTIME';
export const LOAD_OT_STATISTIC = 'LOAD_OT_STATISTIC';
export const LOAD_OVERTIME_SETTING = 'LOAD_OVERTIME_SETTING';
export const LOAD_TEAM_OVERTIME = 'LOAD_TEAM_OVERTIME';
export const LOAD_PAY_RATE_SETTING = 'LOAD_PAY_RATE_SETTING';
export const RESET_OVERTIME_DTO = 'RESET_OVERTIME_DTO'

//Personal Settings
export const GET_COMMONS_PERSONAL_SETTINGS = 'GET_COMMONS_PERSONAL_SETTINGS';
export const GET_DELEGATION_LEAVE = 'GET_DELEGATION_LEAVE';
export const GET_DELEGATION_TIME_CLOCK = 'GET_DELEGATION_TIME_CLOCK';
export const EDIT_DELEGATION_LEAVE = 'EDIT_DELEGATION_LEAVE';
export const EDIT_DELEGATION_TIME_CLOCK = 'EDIT_DELEGATION_TIME_CLOCK';
export const EDIT_COMMONS_PERSONAL_SETTINGS = 'EDIT_COMMONS_PERSONAL_SETTINGS';

//Termination
export const GET_TERMINATIONS = 'GET_TERMINATIONS';
export const TERMINATION = 'TERMINATION';
export const GET_TERMINATION_REASON = 'GET_TERMINATION_REASON';
export const REJOIN = 'REJOIN';

//Geographic
export const LOAD_CITIES = 'LOAD_CITIES';
export const LOAD_DISTRICTS = 'LOAD_DISTRICTS';

//EMERGENCY_CONTACTS
export const GET_EMERGENCY_CONTACTS = 'GET_EMERGENCY_CONTACTS';
export const ADD_EMERGENCY_CONTACT = 'ADD_EMERGENCY_CONTACT';
export const DELETE_EMERGENCY_CONTACT = 'DELETE_EMERGENCY_CONTACT';

//EMERGENCY_CONTACTS_MY_PROFILE
export const GET_EMERGENCY_CONTACTS_PROFILE = 'GET_EMERGENCY_CONTACTS_PROFILE';
export const ADD_EMERGENCY_CONTACT_PROFILE = 'ADD_EMERGENCY_CONTACT_PROFILE';
export const DELETE_EMERGENCY_CONTACT_PROFILE = 'DELETE_EMERGENCY_CONTACT_PROFILE';

//TIMECLOCK
export const GET_CURRENT_STATUS_TIMECLOCK = 'GET_CURRENT_STATUS_TIMECLOCK';
export const CLOCK_TIME = 'CLOCK_TIME';

//HANDSETS
export const GET_HANDSETS = 'GET_HANDSETS';
export const GET_DIALOG_HANDSETS = 'GET_DIALOG_HANDSETS';
export const HANDSET_TYPES = 'HANDSET_TYPES';
export const ASSIGNED_HANDSET = 'ASSIGNED_HANDSET';
export const LOAD_HANDSET_SUMMARY = 'LOAD_HANDSET_SUMMARY';
export const LOAD_STORE_LOCS = 'LOAD_STORE_LOCS';
export const EDIT_HANDSET_TYPE = 'EDIT_HANDSET_TYPE';
export const DELETE_HANDSET = 'DELETE_HANDSET';
export const LOAD_HANDSET = 'LOAD_HANDSET';
export const TRANSFER_HANDSETS = 'TRANSFER_HANDSETS';
export const EDIT_HANDSET = 'EDIT_HANDSET';
export const ASSIGNED_HANDSETS = 'ASSIGNED_HANDSETS';
export const ADD_HANDSET = 'ADD_HANDSET';

//OVERTIMES
export const LOAD_MY_OVERTIMES = 'LOAD_MY_OVERTIMES';
export const LOAD_MY_OVERTIME = 'LOAD_MY_OVERTIME';
export const UPDATE_MY_OVERTIME = 'UPDATE_MY_OVERTIME';
export const UPDATE_MEMBER_OVERTIME = 'UPDATE_MEMBER_OVERTIME';
export const LOAD_OVERTIME_STATISTIC = 'LOAD_OVERTIME_STATISTIC';

//CONTRACTS
export const LOAD_ALL_CONTRACTS = 'LOAD_ALL_CONTRACTS';
export const LOAD_CONTRACT = 'LOAD_CONTRACT';
export const ADD_CONTRACT = 'ADD_CONTRACT';
export const UPDATE_CONTRACT_DTO = 'UPDATE_CONTRACT_DTO';
export const RESET_NEW_CONTRACT_DTO = 'RESET_NEW_CONTRACT_DTO';
export const EDIT_CONTRACT = 'EDIT_CONTRACT';
export const DELETE_CONTRACT = 'DELETE_CONTRACT';

//ORGANIZATION
export const ADD_GROUP_ORGANIZATION = 'ADD_GROUP_ORGANIZATION';
export const EDIT_GROUP_ORGANIZATION = 'EDIT_GROUP_ORGANIZATION';


//NOTIFICATIONS
export const LOAD_NOTIFICATIONS = 'LOAD_NOTIFICATIONS';
export const LOAD_NOTIFICATION_DETAILS = 'LOAD_NOTIFICATION_DETAILS';
export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION';
export const DELETE_NOTIFICATIONS = 'DELETE_NOTIFICATIONS';